### ISSUE TITLE
Asking for help on an error while executing 'make up'

### ISSUE THREAD

**Issue by m-marbukh01** [department-of-veterans-affairs/vets-api#12166]
Currently attempting to run vets-api and was wondering if someone could help.  I am getting the error below while executing `make up`.
```
WARNING: The BUNDLE_ENTERPRISE__CONTRIBSYS__COM variable is not set. Defaulting to a blank string.
Creating vets-api_vets-api_run ... done
Activating bundler (~> 2.4) failed:
Could not find 'bundler' (2.4.8) required by your /srv/vets-api/src/Gemfile.lock.
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.4.8`
Checked in 'GEM_PATH=/srv/vets-api/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle', execute `gem env` for more information

To install the version of bundler this project requires, run `gem install bundler -v '~> 2.4'`
Activating bundler (~> 2.4) failed:
Could not find 'bundler' (2.4.8) required by your /srv/vets-api/src/Gemfile.lock.
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.4.8`
Checked in 'GEM_PATH=/srv/vets-api/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle', execute `gem env` for more information

To install the version of bundler this project requires, run `gem install bundler -v '~> 2.4'`
ERROR: 42
make: *** [db] Error 42
```

Below is the error I get while attempting to execute `bundle update --bundler`

`Fetching gem metadata from https://rubygems.org/.
No credentials found to install Sidekiq Enterprise. This is fine for local development but you may not check in this Gemfile.lock with any Sidekiq gems removed. The README file in this directory contains more information.
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using rake 13.0.6
Using Ascii85 1.1.0
Using concurrent-ruby 1.2.2
Using minitest 5.18.0
Using zeitwerk 2.6.7
Using builder 3.2.4
Using erubi 1.12.0
Using mini_portile2 2.8.1
Using racc 1.6.2
Using crass 1.0.6
Using rack 2.2.6.4
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using marcel 1.0.2
Using mini_mime 1.1.2
Using jsonapi-parser 0.1.1.beta3
Using jsonapi-renderer 0.1.1.beta1
Using rgeo 2.3.0
Using public_suffix 5.0.1
Using adler32 0.0.2
Using afm 0.2.2
Using rexml 3.2.5
Using hashie 3.6.0
Using rspec-support 3.12.0
Using diff-lcs 1.5.0
Using connection_pool 2.3.0
Using redis 4.8.1
Using multipart-post 2.3.0
Using ast 2.4.2
Using attr_extras 6.2.5
Using awesome_print 1.9.2
Using aws-eventstream 1.2.0
Using aws-partitions 1.725.0
Using thread_safe 0.3.6
Using ice_nine 0.11.2
Using httpclient 2.8.3
Using socksify 1.7.1
Using nori 2.6.0
Using bindex 0.8.1
Using blueprinter 0.25.3
Using msgpack 1.6.0
Using brakeman 5.4.1
Using multi_json 1.15.0
Using bundler 2.4.8
Using thor 1.2.1
Using byebug 11.1.3
Using mini_magick 4.12.0
Using ffi 1.15.5
Using ssrf_filter 1.1.1
Using check_in 0.1.0 from source at `modules`
Using claide 1.1.0
Using colored2 3.1.2
Using nap 1.1.0
Using claims_api 0.0.1 from source at `modules`
Using jmespath 1.6.2
Using open4 1.3.4
Using clam_scan 0.0.2
Using cliver 0.3.2
Using coderay 1.1.3
Using ruby-rc4 0.1.5
Using deep_merge 1.2.2
Using dry-initializer 3.1.1
Using matrix 0.4.2
Using content_disposition 1.0.0
Using method_source 1.0.0
Using rchardet 1.8.0
Using no_proxy_fix 0.1.2
Using unicode-display_width 2.4.2
Using database_cleaner-core 2.0.1
Using date_time_precision 0.8.1
Using debase-ruby_core_source 0.10.18
Using libdatadog 0.9.0.1.0
Using debts_api 0.1.0 from source at `modules`
Using dry-inflector 0.3.0
Using declarative 0.0.20
Using dhp_connected_devices 0.1.0 from source at `modules`
Using dogstatsd-ruby 5.5.0
Using unf_ext 0.0.8
Using regexp_parser 2.7.0
Using facilities_api 0.1.0 from source at `modules`
Using docile 1.4.0
Using fastimage 2.2.6
Using mime-types-data 3.2021.1115
Using jwt 2.7.0
Using multi_xml 0.6.0
Using http-accept 1.7.0
Using netrc 0.11.0
Using tilt 2.1.0
Using flipper 0.22.2
Using foreman 0.87.2
Using formatador 0.3.0
Using forms_api 0.1.0 from source at `modules`
Using raabro 1.4.0
Using ruby-progressbar 1.11.0
Using gems 1.2.0
Using memoist 0.16.2
Using os 1.1.4
Using trailblazer-option 0.1.2
Using uber 0.1.0
Using retriable 3.1.2
Using webrick 1.7.0
Using google-protobuf 3.21.12
Using rb-fsevent 0.11.0
Using lumberjack 1.2.8
Using nenv 0.3.0
Using shellany 0.0.1
Using guard-compat 1.2.1
Using json 2.6.3
Using parallel 1.22.1
Using rainbow 3.1.1
Using hana 1.3.7
Using hashdiff 1.0.1
Using hashery 2.1.2
Using health_quest 0.1.0 from source at `modules`
Using holidays 8.6.0
Using iso_country_codes 0.7.8
Using uri_template 0.7.0
Using jwe 0.4.0
Using liquid 5.4.0
Using lockbox 1.1.2
Using meb_api 0.1.0 from source at `modules`
Using net-ssh 7.0.1
Using oj 3.14.2
Using okcomputer 1.18.4
Using openid_auth 0.0.1 from source at `modules`
Using operating_hours 0.1.0
Using optimist 3.0.1
Using ox 2.14.14
Using pdf-core 0.9.0
Using safe_shell 1.1.0
Using ttfunk 1.7.0
Using pg 1.4.6
Using pkce_challenge 1.0.0
Using rack-timeout 0.6.3
Using vcr 6.1.0
Using rubocop-junit-formatter 0.1.4
Using rubyzip 2.3.2
Using script_utils 0.0.4
Using seedbank 0.5.0
Using simplecov-html 0.12.3
Using simplecov_json_formatter 0.1.4
Using staccato 0.5.3
Using statsd-instrument 3.5.6
Using swagger-blocks 3.0.0
Using timecop 0.9.6
Using va_notify 0.1.0 from source at `modules`
Using veteran 0.0.1 from source at `modules`
Using veteran_confirmation 0.0.1 from source at `modules`
Using veteran_verification 0.0.1 from source at `modules`
Using will_paginate 3.3.1
Using aasm 5.5.0
Using i18n 1.12.0
Using tzinfo 2.0.6
Using nokogiri 1.14.2
Using rack-test 1.1.0
Using websocket-driver 0.7.5
Using mail 2.7.1
Using jsonapi 0.1.1.beta6
Using addressable 2.8.1
Using gyoku 1.4.0
Using rspec-core 3.12.1
Using rspec-expectations 3.12.2
Using rspec-mocks 3.12.3
Using sidekiq 6.5.7
Using faraday 0.17.6
Using aws-sigv4 1.5.2
Using descendants_tracker 0.0.4
Using httpi 2.5.0
Using bootsnap 1.16.0
Using bundler-audit 0.9.1
Using ruby-vips 2.1.4
Using cork 0.3.0
Using dry-container 0.11.0
Using dry-core 0.9.1
Using coverband 5.2.5
Using sprockets 4.2.0
Using crack 0.4.5
Using kramdown 2.4.0
Using libddwaf 1.5.1.0.0
Using ethon 0.16.0
Using fakeredis 0.8.0
Using rack-protection 2.1.0
Using rb-inotify 0.10.1
Using parser 3.2.1.0
Using levenshtein-ffi 1.1.0
Using request_store 1.5.1
Using puma 6.1.1
Using rack-attack 6.6.1
Using rack-cors 2.0.0
Using semantic_logger 4.12.0
Using redis-namespace 1.10.0
Using rgeo-geojson 2.1.1
Using warden 1.2.9
Using combine_pdf 1.0.22
Using terminal-table 3.0.2
Using pry 0.14.1
Using unf 0.1.4
Using ecma-re-validator 0.4.0
Using mime-types 3.4.1
Using notifications-ruby-client 5.4.0
Using representable 3.2.0
Using notiffany 0.1.3
Using parallel_tests 4.2.0
Using pg_query 4.2.0
Using yard 0.9.28
Using net-sftp 4.0.0
Using patience_diff 1.2.0
Using pdf-forms 1.3.0
Using pdf-reader 2.11.0
Using prawn 2.4.0
Using rack-vcr 0.1.6
Using simplecov 0.22.0
Using vets_json_schema 20.26.1 from https://github.com/department-of-veterans-affairs/vets-json-schema (at master@4436a9c)
Using activesupport 6.1.7.3
Using loofah 2.19.1
Using akami 1.3.1
Using json-schema 2.8.1
Using rspec 3.12.0
Using apps_api 0.0.1 from source at `modules`
Using aws-sdk-core 3.170.0
Using axiom-types 0.1.1
Using bcp47 0.3.3
Using wasabi 3.7.0
Using breakers 0.6.0
Using image_processing 1.12.2
Using claide-plugins 0.9.2
Using coercible 1.0.0
Using dry-configurable 0.16.1
Using dry-logic 1.3.0
Using xmldsig 0.3.2
Using xmlmapper 0.8.1
Using covid_vaccine 0.1.0 from source at `modules`
Using faraday-http-cache 2.2.0
Using git 1.13.0
Using kramdown-parser-gfm 1.1.0
Using sawyer 0.8.2
Using ddtrace 1.8.0
Using down 5.2.2
Using et-orbi 1.2.7
Using faker 3.1.1
Using faraday_adapter_socks 0.1.1
Using faraday_curl 0.0.2
Using faraday_middleware 0.14.0
Using oauth2 1.4.11
Using flipper-ui 0.22.0
Using fuubar 2.5.1
Using signet 0.17.0
Using listen 3.7.0
Using rubocop-ast 1.26.0
Using rspec-its 1.3.0
Using rspec-retry 0.6.2
Using rspec_junit_formatter 0.6.0
Using ruby-saml 1.15.0
Using sentry-raven 2.13.0
Using sidekiq_alive 2.2.0
Using slack-notify 0.6.0
Using typhoeus 1.4.0
Using vaos 0.1.0 from source at `modules`
Installing mimemagic 0.4.3 with native extensions
Using webmock 3.18.1
Using domain_name 0.5.20190701
Using json_schemer 0.2.24
Using pry-byebug 3.10.1
Using pdf-inspector 1.3.0
Using prawn-table 0.2.2
Using super_diff 0.9.0
Using rails-dom-testing 2.0.3
Using rails-html-sanitizer 1.5.0
Using globalid 1.0.1
Using activemodel 6.1.7.3
Using case_transform 0.2
Using jsonapi-serializer 2.2.0
Using betamocks 0.9.1 from https://github.com/department-of-veterans-affairs/betamocks (at master@e4b71ca)
Using factory_bot 6.2.0
Using flipper-active_support_cache_store 0.22.2
Using kms_encrypted 1.4.0
Using pundit 2.3.0
Using rspec-instrumentation-matcher 0.0.9
Using utf8-cleaner 1.0.0
Using aws-sdk-kms 1.63.0
Using aws-sdk-sns 1.60.0
Using savon 2.12.0
Using dry-types 1.6.1
Using fhir_dstu2_models 1.1.1
Using fhir_models 4.2.1
Using fhir_stu3_models 3.1.1
Using virtus 2.0.0
Using octokit 4.21.0
Using fitbit_api 0.15.1
Using fugit 1.8.1
Using googleauth 1.3.0
Using govdelivery-tms 2.8.4
Using guard 2.18.0
Using rubocop 1.44.1
Using restforce 5.3.1
Using shrine 3.4.0
Using actionview 6.1.7.3
Using activejob 6.1.7.3
Using activerecord 6.1.7.3
Using appeals_api 0.0.1 from source at `modules`
Using carrierwave 2.2.3
Using xmlenc 0.8.0
Using date_validator 0.12.0
Using http-cookie 1.0.4
Using prawn-markup 0.3.7
Using actionpack 6.1.7.3
Using activerecord-import 1.4.1
Using rgeo-activerecord 7.0.1
Using aws-sdk-s3 1.119.1
Using dry-schema 1.11.3
Using danger 8.6.1
Using database_cleaner-active_record 2.0.1
Using dry-struct 1.5.2
Using flipper-active_record 0.22.1
Using google-apis-core 0.11.0
Using guard-rspec 4.7.3
Using guard-rubocop 1.5.0
Using paper_trail 14.0.0
Using pg_search 2.3.6
Using rubocop-capybara 2.17.0
Using rubocop-rails 2.18.0
Using rubocop-thread_safety 0.4.4
Using rufus-scheduler 3.8.2
Using strong_migrations 1.4.4
Using warden-github 1.3.2
Using with_advisory_lock 4.6.0
Using actioncable 6.1.7.3
Using activestorage 6.1.7.3
Using actionmailer 6.1.7.3
Using active_model_serializers 0.10.4.vsp from https://github.com/department-of-veterans-affairs/active_model_serializers (at master@19015ca)
Using activerecord-postgis-adapter 7.1.1
Using apivore 1.6.2.vsp from https://github.com/department-of-veterans-affairs/apivore (at master@b5b6c98)
Using bgs_ext 0.21.3 from https://github.com/department-of-veterans-affairs/bgs-ext.git (at master@aaa0e7e)
Using carrierwave-aws 1.5.0
Using connect_vbms 1.2.0 from https://github.com/department-of-veterans-affairs/connect_vbms.git (at master@43654a0)
Using railties 6.1.7.3
Using sprockets-rails 3.4.2
Using rest-client 2.1.0
Using vba_documents 1.0.0 from source at `modules`
Using dry-validation 1.9.0
Using database_cleaner 2.0.1
Using actionmailbox 6.1.7.3
Using actiontext 6.1.7.3
Using google-apis-discovery_v1 0.13.0
Using rubocop-rspec 2.18.1
Using sidekiq-scheduler 5.0.2
Using va_forms 0.0.1 from source at `modules`
Using factory_bot_rails 6.2.0
Using fhir_client 5.0.3
Using rails_semantic_logger 4.11.0
Using rspec-rails 6.0.1
Using rswag-specs 2.8.0
Using rswag-ui 2.8.0
Using web-console 4.2.0
Using config 4.1.0
Using mobile 0.1.0 from source at `modules`
Using rails 6.1.7.3
Using google-apis-generator 0.12.0
Using covid_research 0.1.0 from source at `modules`
Using google-api-client 0.53.0
Using mocked_authentication 0.1.0 from source at `modules`
Using my_health 0.1.0 from source at `modules`
Using olive_branch 4.0.1
Using rails-session_cookie 0.3.0
Using test_user_dashboard 0.1.0 from source at `modules`
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/mike/.rvm/gems/ruby-2.7.6/gems/mimemagic-0.4.3/ext/mimemagic
/Users/mike/.rvm/rubies/ruby-2.7.6/bin/ruby -I/Users/mike/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0 -rrubygems
/Users/mike/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/rake-13.0.6/exe/rake
RUBYARCHDIR\=/Users/mike/.rvm/gems/ruby-2.7.6/extensions/x86_64-darwin-22/2.7.0/mimemagic-0.4.3
RUBYLIBDIR\=/Users/mike/.rvm/gems/ruby-2.7.6/extensions/x86_64-darwin-22/2.7.0/mimemagic-0.4.3
rake aborted!
Could not find MIME type database in the following locations: ["/usr/local/share/mime/packages/freedesktop.org.xml",
"/opt/homebrew/share/mime/packages/freedesktop.org.xml", "/opt/local/share/mime/packages/freedesktop.org.xml",
"/usr/share/mime/packages/freedesktop.org.xml"]

Ensure you have either installed the shared-mime-info package for your distribution, or
obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to the location
of that file.
/Users/mike/.rvm/gems/ruby-2.7.6/gems/mimemagic-0.4.3/ext/mimemagic/Rakefile:15:in `locate_mime_database'
/Users/mike/.rvm/gems/ruby-2.7.6/gems/mimemagic-0.4.3/ext/mimemagic/Rakefile:26:in `block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/mike/.rvm/gems/ruby-2.7.6/gems/mimemagic-0.4.3 for inspection.
Results logged to /Users/mike/.rvm/gems/ruby-2.7.6/extensions/x86_64-darwin-22/2.7.0/mimemagic-0.4.3/gem_make.out

  /Users/mike/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:102:in `run'
  /Users/mike/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/ext/rake_builder.rb:28:in `build'
  /Users/mike/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:170:in `build_extension'
  /Users/mike/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:204:in `block in build_extensions'
  /Users/mike/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:201:in `each'
  /Users/mike/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:201:in `build_extensions'
  /Users/mike/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems/installer.rb:843:in `build_extensions'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/source/rubygems.rb:200:in `install'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/worker.rb:62:in `apply_func'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/worker.rb:54:in `loop'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/worker.rb:54:in `process_queue'
  /Users/mike/.rvm/gems/ruby-2.7.6/gems/bundler-2.4.8/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing mimemagic (0.4.3), and Bundler cannot continue.

In Gemfile:
  mimemagic`

Next attempted to execute `gem install mimemagic --source 'https://rubygems.org/'` but wasn't successful.

**Comment by m-marbukh01** [comment]
The line `gem list | grep "bundle"` produces `bundler (2.4.9, 2.4.8, default: 2.1.4)`
