### ISSUE TITLE
uninitialized constant EMIS::Models::DeploymentLocation

### ISSUE THREAD

**Issue by abhijitvk** [department-of-veterans-affairs/vets-api#2242]
@djmunoz1 @lihanli : While testing pre-fill information for the new form 4142 locally, I came across an error as below

Rails -- uninitialized constant EMIS::Models::DeploymentLocation.
14:30:37 web.1  | 2018-08-27 14:30:37.083924 E [10:69928254381580 sentry_logging.rb:42] [[]] Rails -- /src/vets-api/lib/emis/responses/get_deployment_response.rb:24:in `item_schema'
14:30:37 web.1  | /src/vets-api/lib/emis/responses/response.rb:48:in `build_item'
14:30:37 web.1  | /src/vets-api/lib/emis/responses/response.rb:12:in `block in items'
14:30:37 web.1  | /src/vets-api/lib/emis/responses/response.rb:11:in `map'
14:30:37 web.1  | /src/vets-api/lib/emis/responses/response.rb:11:in `items'
14:30:37 web.1  | /src/vets-api/app/models/emis_redis/model.rb:24:in `items_from_response'
14:30:37 web.1  | /src/vets-api/app/models/emis_redis/military_information.rb:201:in `deployments'
14:30:37 web.1  | /src/vets-api/app/models/emis_redis/military_information.rb:163:in `post_nov111998_combat'

@lihanli : On investigation, I noticed that EMIS::Models::DeploymentLocation file has been named as `deployment.rb` VS `deployment_location.rb` which is likely root cause of the issue. Renamed & tested it locally which seems to resolve the issue. We must rename file name from vets-api/lib/emis/models/deployment.rb  - to - vets-api/lib/emis/models/deployment_location.rb unless the class is named differently in the definition. If you want to review the change, I have it on one of our WIP branch : https://github.com/department-of-veterans-affairs/vets-api/tree/4142-api-async

**Comment by abhijitvk** [comment]
@lihanli @djmunoz1 : Please do hold off on this issue. It seems that just renaming it won't be solve the issue as we use the model with  'emis/models/deployment'. I will close the issue for now, if needed will create a new one.
