### ISSUE TITLE
Parse 500 response and retry on SAML metadata failure

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/vets-api#563]
We attempt to load SAML metadata from id.me once on app startup. If this fails the app will throw the following error:

`REXML::ParseException: Missing end tag for 'meta' (got "head")`

1. Get an example 500 from id.me
2. Add logic to parse a possible 500
3. Retry _n_ times (3? this could be configurable)

**Comment by kreek** [comment]
adding stack trace:

```
REXML::ParseException: Missing end tag for 'meta' (got "head")
Line: 63
Position: 2950
Last 80 unconsumed characters:
  from rexml/parsers/baseparser.rb:341:in `pull_event'
  from rexml/parsers/baseparser.rb:185:in `pull'
  from rexml/parsers/treeparser.rb:23:in `parse'
  from rexml/document.rb:288:in `build'
  from rexml/document.rb:45:in `initialize'
  from onelogin/ruby-saml/idp_metadata_parser.rb:43:in `new'
  from onelogin/ruby-saml/idp_metadata_parser.rb:43:in `parse'
  from lib/saml/settings_service.rb:45:in `create_settings_from_metadata'
  from lib/saml/settings_service.rb:12:in `initialize'
  from app/controllers/application_controller.rb:97:in `new'
  from app/controllers/application_controller.rb:97:in `saml_settings'
```

**Comment by jcmeloni** [comment]
@robbiethegeek is this something planned for active working? if so, what tags do we need here to surface that?

**Comment by kreek** [comment]
@jcmeloni fixed by https://github.com/department-of-veterans-affairs/vets-api/pull/569
